### PR TITLE
[3.x] Getting specific key from data

### PR DESCRIPTION
**Pull request by omalizadeh**

### CODE REVIEW

**Comment by Hebrahimzadeh** [comment]
in both commits changed test method names to camelCase it is ok? and is it convention?

**Comment by omalizadeh** [comment]
> in both commits changed test method names to camelCase it is ok? and is it convention?

It will be the new convention, like other class methods. console output automatically converts it to readable sentences.

**Comment by Hebrahimzadeh** [comment]
@mhabedini 
get specific data from the `data` response method is ok?
Because I said them before.

**Comment by Hebrahimzadeh** [comment]
I think need to get detail from data from the response.

**Review by mhabedini — APPROVED** [review]

**Pull request merged**
